import { Inter } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import { LocaleProvider } from "../context/LocaleContext";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "prototype",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={`flex ${inter.className}`}>
        <LocaleProvider>{children}</LocaleProvider>
      </body>
    </html>
  );
}
